name: ci

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened # default
      - reopened # default
      - synchronize # default
      - ready_for_review
    paths:
      - .github/workflows/**
      - package.json
      - apps/www/src/**
      - apps/www/e2e/**
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/**
      - package.json
      - apps/www/src/**
      - apps/www/e2e/**

jobs:
  code-quality:
    name: Code Quality
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node
      - run: npx prettier --check . && pnpm lint && cd apps/www && npx eslint .
    timeout-minutes: 5

  unit-test:
    name: Unit Test
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node
      - run: pnpm turbo test --filter=www
    timeout-minutes: 5

  e2e-test:
    name: E2E Test
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node
      - run: pnpm --filter www exec playwright install chromium
      - run: pnpm turbo build --filter=www
      - run: pnpm --filter www test:e2e
      - name: Upload Playwright report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: always()
        with:
          name: playwright-report
          path: apps/www/playwright-report/
          retention-days: 30
    timeout-minutes: 10
